// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package waterslide_bufs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Resource struct {
	_tab flatbuffers.Table
}

func GetRootAsResource(buf []byte, offset flatbuffers.UOffsetT) *Resource {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Resource{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsResource(buf []byte, offset flatbuffers.UOffsetT) *Resource {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Resource{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Resource) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Resource) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Resource) ResourceProto() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Resource) Gsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Resource) MutateGsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Resource) Version() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ResourceStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ResourceAddResourceProto(builder *flatbuffers.Builder, resourceProto flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(resourceProto), 0)
}
func ResourceAddGsn(builder *flatbuffers.Builder, gsn uint64) {
	builder.PrependUint64Slot(1, gsn, 0)
}
func ResourceAddVersion(builder *flatbuffers.Builder, version flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(version), 0)
}
func ResourceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
